version: '3'
services:
  php:
    build: 
      context: .
      dockerfile: backend.dockerfile
    container_name: "php"
    volumes:
      - ./widget:/var/www/html
    ports:
      - 8080:80
    networks:
      - bridge
    
networks:
  bridge:
    driver: bridge
